import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Microfrontend1 from "@/components/Microfrontend1";
import Microfrontend2 from "@/components/Microfrontend2";
import { Box, Grid, Typography } from "@mui/material";
import { useMicrofrontendContext } from "@/context/MicrofrontendContext";

const inter = Inter({ subsets: ["latin"] });

export default function Container() {
  const { user } = useMicrofrontendContext();

  return (
    <>
      <Head>
        <title>Microfrontend App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Box mb={3}>
          <Typography variant="body1">
            Login: {user.email ? user.email : "Offline"}
          </Typography>
        </Box>
        <Grid container spacing={3}>
          <Grid item xs={12} md={6}>
            <Microfrontend1 />
          </Grid>
          <Grid item xs={12} md={6}>
            <Microfrontend2 />
          </Grid>
        </Grid>
      </main>
    </>
  );
}
